SELECT
    T0.CardCode ,
    T0.CardName ,
  CASE
      WHEN SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) < 0 THEN T0.DocTotal ELSE 0 END) = 0 THEN 0
      ELSE SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) < 0 THEN T0.DocTotal * DATEDIFF(DAY, T0.DocDueDate, GETDATE()) ELSE 0 END) / SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) < 0 THEN T0.DocTotal ELSE 0 END) 
      END *-1 AS 'Average Pending Day',
    CASE
        WHEN SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) >= 0 THEN T0.DocTotal ELSE 0 END) = 0 THEN 0
        ELSE SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) >= 0 THEN T0.DocTotal * DATEDIFF(DAY, T0.DocDueDate, GETDATE()) ELSE 0 END) / SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) >= 0 THEN T0.DocTotal ELSE 0 END)
    END AS 'Average Expired Day',
    SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) < 0 THEN T0.DocTotal ELSE 0 END) AS 'Undue Amount',
    SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) >= 0 AND DATEDIFF(DAY, T0.DocDueDate, GETDATE()) <= 7 THEN T0.DocTotal ELSE 0 END) AS '0-7 Days',
    SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) > 7 AND DATEDIFF(DAY, T0.DocDueDate, GETDATE()) <= 30 THEN T0.DocTotal ELSE 0 END) AS '8-30 Days',
    SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) > 30 AND DATEDIFF(DAY, T0.DocDueDate, GETDATE()) <= 60 THEN T0.DocTotal ELSE 0 END) AS '31-60 Days',
    SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) > 60 AND DATEDIFF(DAY, T0.DocDueDate, GETDATE()) <= 90 THEN T0.DocTotal ELSE 0 END) AS '61-90 Days',
    SUM(CASE WHEN DATEDIFF(DAY, T0.DocDueDate, GETDATE()) > 90 THEN T0.DocTotal ELSE 0 END) AS '90+ Days'
FROM
    OINV T0
WHERE
  T0.DocType = 'I'
  AND T0.DocStatus = 'O'
GROUP BY
    T0.CardCode, T0.CardName
